FROM php:8.2.1-apache

# Instalar dependências do sistema e extensões PHP necessárias
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libzip-dev \
    libpng-dev \
    && docker-php-ext-install pdo pdo_mysql mysqli zip    \
    && rm -rf /var/lib/apt/lists/*

# Instalar Composer globalmente
RUN curl -sS https://getcomposer.org/installer |  php && \
mv composer.phar /usr/local/bin/composer && \
chmod +x /usr/local/bin/composer

# Habilitar mod_rewrite do Apache
RUN a2enmod rewrite

# Teste se o composer foi instalado
RUN composer --version

COPY . .
# Define diretório de trabalho
WORKDIR /var/www/html

# Instala dependências (se existir composer.json)
RUN if [ -f composer.json ]; then composer install --no-interaction --prefer-dist; fi

RUN chmod +x start.sh

EXPOSE 80

CMD ["apache2-foreground"]

